_VERSION: 3 # Do not touch this line!
lastFmUsername: ""

smallImage: profile # What to show on the small image
# lastfm: "Scrobbling now on Last.fm" with Last.fm logo
# profile: "Scrobbling as X on Last.fm" with profile picture
# none: No small image

# Buttons to show on the Rich Presence
button1: song
button2: profile
# song: "View Song"
# artist: "View Artist"
# profile: "Last.fm Profile"
# github: "Last.fm Rich Presence"
# none: No button

# Disable when another app's Rich Presence is detected
# Requires joining https://discord.gg/lanyard
disableOnPresence:
  any: false
  listening: true
  custom: [] # Application IDs

# lastFmApiKey: ""
# discordClientId: ""
