_VERSION: 4 # Do not touch this line!

provider: lastfm # lastfm, listenbrainz
username: ""

smallImage: profile # What to show on the small image
# logo: "Scrobbling on X" with provider logo
# profile: "Scrobbling as X on X" with profile picture
# none: No small image

# Buttons to show on the Rich Presence
button1: song
button2: profile
# song: "View Song"
# profile: "<Provider> Profile"
# github: "Scrobble Rich Presence"
# none: No button

# Disable when another app's Rich Presence is detected
# Requires joining https://discord.gg/lanyard
disableOnPresence:
  any: false
  listening: true
  custom: # Application IDs or names (case-insensitive)
    - "12345678901234567890" # "" is required
    - Apple Music
# lastFmApiKey: ""
# discordClientId: ""
